import {
  ILightProduct,
  ISoundProduct,
  LightCategory,
  SoundCategory,
} from './IProduct';
import { Department } from './IUser';

export const navLists = {
  worker: [
    { path: '/work/my-jobs', label: 'My Jobs' },
    { path: '/work/updates', label: 'Updates' },
    { path: '/work/profile', label: 'Profile' },
  ],
};

export const sideBarLists = {
  admin: [
    { path: '/', label: 'Dashboard' },
    { path: '/products', label: 'Products' },
    { path: '/jobs', label: 'Jobs' },
    { path: '/crew', label: 'Crew' },
  ],
  manager: [
    { path: '/', label: 'Dashboard' },
    { path: '/gear', label: 'Gear' },
    { path: '/jobs', label: 'Jobs' },
  ],
  worker: [
    { path: '/', label: 'Dashboard' },
    { path: '/jobs', label: 'Jobs' },
  ],
};
export const accordionItems = [
  { label: 'Update', path: '/update' },
  { label: 'Add New', path: '/create' },
  { label: 'Delete', path: '/delete' },
];

export const DUMMY_SOUND_PRODUCTS: ISoundProduct[] = [
  {
    name: 'AL90',
    quantity: {
      total: 8,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 8,
    },
    department: Department.SOUND,
    brand: 'D&B',
    subCategory: SoundCategory.SPEAKER,
  },
  {
    name: 'VG-SUB',
    quantity: {
      total: 6,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 6,
    },
    department: Department.SOUND,
    brand: 'D&B',
    subCategory: SoundCategory.SPEAKER,
  },
  {
    name: 'MAX2',
    quantity: {
      total: 2,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 2,
    },
    department: Department.SOUND,
    brand: 'D&B',
    subCategory: SoundCategory.SPEAKER,
  },
  {
    name: 'ETX 15',
    quantity: {
      total: 4,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 4,
    },
    department: Department.SOUND,
    brand: 'Electro-Voice',
    subCategory: SoundCategory.SPEAKER,
  },
  {
    name: 'DINACOURD 12',
    quantity: {
      total: 2,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 2,
    },
    department: Department.SOUND,
    brand: 'Electro-Voice',
    subCategory: SoundCategory.SPEAKER,
  },
  {
    name: 'D20',
    quantity: {
      total: 2,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 2,
    },
    department: Department.SOUND,
    brand: 'D&B',
    subCategory: SoundCategory.AMP,
  },
  {
    name: 'D40',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.SOUND,
    brand: 'D&B',
    subCategory: SoundCategory.AMP,
  },
  {
    name: 'GroundStack Plate',
    quantity: {
      total: 4,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 4,
    },
    department: Department.SOUND,
    brand: 'D&B',
    subCategory: SoundCategory.SPEAKER_GEAR,
  },
  {
    name: 'Horizontal Flown Rig',
    quantity: {
      total: 2,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 2,
    },
    department: Department.SOUND,
    brand: 'D&B',
    subCategory: SoundCategory.SPEAKER_GEAR,
  },
  {
    name: 'Vertical Flown Rig',
    quantity: {
      total: 2,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 2,
    },
    department: Department.SOUND,
    brand: 'D&B',
    subCategory: SoundCategory.SPEAKER_GEAR,
  },
  {
    name: 'Super Lift',
    quantity: {
      total: 2,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 2,
    },
    department: Department.SOUND,
    brand: 'any',
    subCategory: SoundCategory.SPEAKER_GEAR,
  },
  {
    name: 'Floor Stands',
    quantity: {
      total: 2,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 2,
    },
    department: Department.SOUND,
    brand: 'K&M',
    subCategory: SoundCategory.SPEAKER_GEAR,
  },
  {
    name: 'HD96',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.SOUND,
    brand: 'Midas',
    subCategory: SoundCategory.MIXER,
  },
  {
    name: 'LV1',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.SOUND,
    brand: 'Waves',
    subCategory: SoundCategory.MIXER,
  },
  {
    name: 'DL231',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.SOUND,
    brand: 'Midas',
    subCategory: SoundCategory.SB,
  },
  {
    name: 'DL151',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.SOUND,
    brand: 'Midas',
    subCategory: SoundCategory.SB,
  },
  {
    name: 'Axient',
    quantity: {
      total: 2,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 2,
    },
    department: Department.SOUND,
    brand: 'Shure',
    subCategory: SoundCategory.WIRELESS,
  },
  {
    name: 'In Ear Monitor',
    quantity: {
      total: 8,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 8,
    },
    department: Department.SOUND,
    brand: 'Sehnhiser',
    subCategory: SoundCategory.WIRELESS,
  },
  {
    name: 'Drums',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.SOUND,
    brand: 'any',
    subCategory: SoundCategory.BACKLINE,
  },
  {
    name: 'Guitar Amp',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.SOUND,
    brand: 'Fender',
    subCategory: SoundCategory.BACKLINE,
  },
  {
    name: 'Bass Amp',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.SOUND,
    brand: 'GK',
    subCategory: SoundCategory.BACKLINE,
  },
];

export const DUMMY_Light_PRODUCTS: ILightProduct[] = [
  {
    name: 'AROLLA',
    quantity: {
      total: 8,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 8,
    },
    department: Department.LIGHT,
    brand: 'any',
    subCategory: LightCategory.SMART,
  },
  {
    name: '150',
    quantity: {
      total: 12,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 12,
    },
    department: Department.LIGHT,
    brand: 'any',
    subCategory: LightCategory.SMART,
  },
  {
    name: 'Mini Q7',
    quantity: {
      total: 8,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 8,
    },
    department: Department.LIGHT,
    brand: 'any',
    subCategory: LightCategory.SMART,
  },
  {
    name: 'WL Led',
    quantity: {
      total: 20,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 20,
    },
    department: Department.LIGHT,
    brand: 'any',
    subCategory: LightCategory.LED,
  },
  {
    name: 'Sunstrip',
    quantity: {
      total: 8,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 8,
    },
    department: Department.LIGHT,
    brand: 'any',
    subCategory: LightCategory.LED,
  },
  {
    name: 'Smoke Machine',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.LIGHT,
    brand: 'any',
    subCategory: LightCategory.SMOKE,
  },
  {
    name: 'Par 64',
    quantity: {
      total: 8,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 8,
    },
    department: Department.LIGHT,
    brand: 'any',
    subCategory: LightCategory.LED,
  },
  {
    name: 'PITA',
    quantity: {
      total: 8,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 8,
    },
    department: Department.LIGHT,
    brand: 'D&B',
    subCategory: LightCategory.LED,
  },
  {
    name: '2 Light',
    quantity: {
      total: 2,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 2,
    },
    department: Department.LIGHT,
    brand: 'any',
    subCategory: LightCategory.LED,
  },
  {
    name: '40W Led',
    quantity: {
      total: 8,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 8,
    },
    department: Department.LIGHT,
    brand: 'any',
    subCategory: LightCategory.LED,
  },
  {
    name: 'Spliter ATRNET',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.LIGHT,
    brand: 'any',
    subCategory: LightCategory.SPLITER,
  },
  {
    name: 'Spliter TEC',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.LIGHT,
    brand: 'any',
    subCategory: LightCategory.SPLITER,
  },
  {
    name: 'MA on PC',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.LIGHT,
    brand: 'MA',
    subCategory: LightCategory.CONTROLLERS,
  },
  {
    name: 'TIPESH',
    quantity: {
      total: 1,
      onWork: 0,
      onRepair: 0,
      broken: 0,
      remain: 1,
    },
    department: Department.LIGHT,
    brand: 'any',
    subCategory: LightCategory.CONTROLLERS,
  },
];

export * from './IJob';
export * from './IProduct';
export * from './IUser';
